api:
  budget:
    path: "/api/budget"

debug: true
server:
  port: 3000
spring:
  datasource:
    url: ${URL_DB}
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: postgresql
      mode: always
    output:
      ansi:
        enabled: always
  config:
    import: file:./src/main/resources/application-dev.yml
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR